apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-namespaced
  namespace: games
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
