name: Build & Test

on:
  push:
    branches:
    - main

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: "1.22.0"

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      run: go build -v -ldflags "-X main.Version=${GITHUB_SHA::7}" -o kubectl-browse-pvc .

    - name: Fix permissions
      run: chmod +x ./kubectl-browse-pvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-browse-pvc-darwin
        path: |
          ./kubectl-browse-pvc
          LICENSE
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: "1.22.0"

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      run: go build -v -ldflags "-X main.Version=${GITHUB_SHA::7}" -o kubectl-browse-pvc .

    - name: Fix permissions
      run: chmod +x ./kubectl-browse-pvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-browse-pvc-linux
        path: |
          ./kubectl-browse-pvc
          LICENSE


