name: Build pvcb

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
    - name: Check out Code
      uses: actions/checkout@v4.0.0
    - name: Get Dependencies
      run: go mod download
    - name: Build
      run: go build -v .
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: binary
        path: |
          ./pvcb
      
      
      

