name: Build kubectl-browse-pvc

on:
  push:
    branches:
    - main

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.20.5'

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      run: go build -v -o kubectl-browse_pvc .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: kubectl-browse-pvc-darwin
        path: |
          ./kubectl-browse_pvc
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.20.5'

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      run: go build -v -o kubectl-browse_pvc .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: kubectl-browse-pvc-linux
        path: |
          ./kubectl-browse_pvc




